### ISSUE TITLE
Office dataframe returned from getMPs function

### ISSUE THREAD

**Issue by kiwiting** [jblumenau/twfyR#2]
Hi,

I'm not sure if it is an issue or is by design, but when I try calling a list of MPs on a given date, the dataframe office seems to be returning a list of office being occupied by those on the list at present instead of the search date.

`Library(twfyR)

MPs2011 <- getMPs(date = '2011-06-01')

View(MPs2011$office)`

The dataframe returned showed David Davis as Brexit Secretary and David Cameron have no position.

**Comment by jblumenau** [comment]
Thanks Kiwi for alerting me.

Yeah, that's a bug. It's because the TWFY XML links current posts with MPs in all periods. I'll try and get round to fixing this but it's unlikely to be for a couple of weeks I'm afraid.

**Comment by jblumenau** [comment]
In fact, looking into this a bit more, it doesn't seem that TWFY provides the historical office data in any convenient way. The `member` lists should be fine, though. So if you are going to go on and collect the speeches of each member with `getDebates` then the office information should be included in that output.

E.g.

```
> MPs2011 <- getMPs(date = '2011-06-01')

> MPs2011$members[MPs2011$members$name == "David Cameron",]
    member_id person_id          name        party constituency
     40665     10777 David Cameron Conservative       Witney

> cameron_speeches <- getDebates(person = 10777, type = "commons", complete_call = T)
> dim(cameron_speeches)
[1] 11871    28
> unique(cameron_speeches$position)
[1] "The Prime Minister"                                 "Leader of Her Majesty's Official Opposition"        "Shadow Secretary of State for Education"           
[4] NA                                                   "Shadow Minister (Communities and Local Government)" "Deputy Chair, Conservative Party"                  
[7] "Shadow Minister (Privy Council Office)"     

```

**Comment by kiwiting** [comment]
Hi Jack

Thanks for the response, its really helpful.

Yes, I don't think it will affect scraping the past speeches of MPs, I just thought it would be handy if I could use the office dataframe from getMPs create snapshots of MPs offices to create a panel for other purposes.

**Comment by jblumenau** [comment]
Yeah, sadly not. This is something I have been working on separately and intend to add here in the not-too-distant future.
