### ISSUE TITLE
getDebates() search argument

### ISSUE THREAD

**Issue by laurebokobza** [jblumenau/twfyR#4]
Hi, 
A couple of questions/issues regarding the getDebates() function: 

(i) when providing the search argument "housing" in the getDebates() function, stemming results in the API returning all MP interventions containing the word "hous" in their body - which is nearly all of them. i.e. when running
`speeches_housing_all <- getDebates(type = "commons", search = "housing", order = "d")
` 
the data.frame returned is such that "hous" is present in all observations for "body" but "housing" is not. The TWFY advanced search suggests using quotation marks to avoid stemming, does your function also had a way around this? 

(ii) alternatively, is there any way for getDebates() to search the content of the debate title ("parent" column in the returned data.frame), rather than the body of text? (returning the same list of results as when searching for a specific term on Hansard)

Many thanks!

**Comment by jblumenau** [comment]
Thanks for this. I've just pushed a change that allows for exact searching.

Try:

````
> speeches_housing_all <- getDebates(type = "commons", search = 'housing', order = "d", exact = TRUE)
> table(grepl("housing",speeches_housing_all$body, ignore.case = TRUE))
TRUE 
 946 
````

I'm not sure there is a way of only searching the parent field. I will look into it, but I think it is unlikely.
