### ISSUE TITLE
search argument in getDebates() function

### ISSUE THREAD

**Issue by aminaharrath** [jblumenau/twfyR#6]
When I use "Palestine" in the search argument I get a list of speeches that date back to 1967, but when I replace it with "Israel", it only shows speeches that date back to 2004. My hunch is that this is because of the limit of 1,000 results returned. My goal is to get a list of speeches recorded between 1973-1987 with the term "Israel"- what's the best way to do this without using up my call allowance? 

Thank you very much in advance!

**Comment by jblumenau** [comment]
This is because you are not using the `complete_call` argument in the `getDebates()` function. Compare this:

```
palestine_debates <- getDebates(type = "commons",
                                search = "Palestine")

israel_debates <- getDebates(type = "commons",
                             search = "Israel")

> range(palestine_debates$hdate)
[1] "1967-07-17" "2021-01-28"
> range(israel_debates$hdate)
[1] "2004-07-14" "2021-04-19"
```

```
palestine_debates <- getDebates(type = "commons",
                                search = "Palestine",
                                complete_call = TRUE)

israel_debates <- getDebates(type = "commons",
                             search = "Israel",
                             complete_call = TRUE)

> range(palestine_debates$hdate)
[1] "1919-02-11" "2021-01-28"
> range(israel_debates$hdate)
[1] "1919-05-23" "2021-04-19"
```

Note that the `complete_call` argument will use up your API allowance pretty quickly if there are lots of pages to iterate over.
